// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package azuredevops

import (
	"encoding/json"
	"time"
)

// GetLinks returns the Links field.
func (a *AuthorRef) GetLinks() *Links {
	if a == nil {
		return nil
	}
	return a.Links
}

// GetController returns the Controller field.
func (b *Build) GetController() *BuildController {
	if b == nil {
		return nil
	}
	return b.Controller
}

// GetDeleted returns the Deleted field if it's non-nil, zero value otherwise.
func (b *Build) GetDeleted() bool {
	if b == nil || b.Deleted == nil {
		return false
	}
	return *b.Deleted
}

// GetDeletedBy returns the DeletedBy field.
func (b *Build) GetDeletedBy() *IdentityRef {
	if b == nil {
		return nil
	}
	return b.DeletedBy
}

// GetLastChangedBy returns the LastChangedBy field.
func (b *Build) GetLastChangedBy() *IdentityRef {
	if b == nil {
		return nil
	}
	return b.LastChangedBy
}

// GetOrchestrationPlan returns the OrchestrationPlan field.
func (b *Build) GetOrchestrationPlan() *buildOrchestrationPlanSchema {
	if b == nil {
		return nil
	}
	return b.OrchestrationPlan
}

// GetQueuePosition returns the QueuePosition field if it's non-nil, zero value otherwise.
func (b *Build) GetQueuePosition() int {
	if b == nil || b.QueuePosition == nil {
		return 0
	}
	return *b.QueuePosition
}

// GetRetainedByRelease returns the RetainedByRelease field if it's non-nil, zero value otherwise.
func (b *Build) GetRetainedByRelease() bool {
	if b == nil || b.RetainedByRelease == nil {
		return false
	}
	return *b.RetainedByRelease
}

// GetTriggerBuild returns the TriggerBuild field.
func (b *Build) GetTriggerBuild() *Build {
	if b == nil {
		return nil
	}
	return b.TriggerBuild
}

// GetRepository returns the Repository field.
func (b *BuildDefinition) GetRepository() *Repository {
	if b == nil {
		return nil
	}
	return b.Repository
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (e *Event) GetCreatedDate() time.Time {
	if e == nil || e.CreatedDate == nil {
		return time.Time{}
	}
	return *e.CreatedDate
}

// GetDetailedMessage returns the DetailedMessage field.
func (e *Event) GetDetailedMessage() *Message {
	if e == nil {
		return nil
	}
	return e.DetailedMessage
}

// GetEventType returns the EventType field if it's non-nil, zero value otherwise.
func (e *Event) GetEventType() string {
	if e == nil || e.EventType == nil {
		return ""
	}
	return *e.EventType
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (e *Event) GetID() string {
	if e == nil || e.ID == nil {
		return ""
	}
	return *e.ID
}

// GetMessage returns the Message field.
func (e *Event) GetMessage() *Message {
	if e == nil {
		return nil
	}
	return e.Message
}

// GetNotificationID returns the NotificationID field if it's non-nil, zero value otherwise.
func (e *Event) GetNotificationID() int {
	if e == nil || e.NotificationID == nil {
		return 0
	}
	return *e.NotificationID
}

// GetRawPayload returns the RawPayload field if it's non-nil, zero value otherwise.
func (e *Event) GetRawPayload() json.RawMessage {
	if e == nil || e.RawPayload == nil {
		return json.RawMessage{}
	}
	return *e.RawPayload
}

// GetResourceContainers returns the ResourceContainers field.
func (e *Event) GetResourceContainers() *ResourceContainers {
	if e == nil {
		return nil
	}
	return e.ResourceContainers
}

// GetResourceVersion returns the ResourceVersion field if it's non-nil, zero value otherwise.
func (e *Event) GetResourceVersion() string {
	if e == nil || e.ResourceVersion == nil {
		return ""
	}
	return *e.ResourceVersion
}

// GetSubscriptionID returns the SubscriptionID field if it's non-nil, zero value otherwise.
func (e *Event) GetSubscriptionID() string {
	if e == nil || e.SubscriptionID == nil {
		return ""
	}
	return *e.SubscriptionID
}

// GetAvatar returns the Avatar field.
func (l *Links) GetAvatar() *Avatar {
	if l == nil {
		return nil
	}
	return l.Avatar
}

// GetAuthor returns the Author field.
func (m *MergeCommit) GetAuthor() *Committer {
	if m == nil {
		return nil
	}
	return m.Author
}

// GetCommitter returns the Committer field.
func (m *MergeCommit) GetCommitter() *Committer {
	if m == nil {
		return nil
	}
	return m.Committer
}

// GetHTML returns the HTML field if it's non-nil, zero value otherwise.
func (m *Message) GetHTML() string {
	if m == nil || m.HTML == nil {
		return ""
	}
	return *m.HTML
}

// GetMarkdown returns the Markdown field if it's non-nil, zero value otherwise.
func (m *Message) GetMarkdown() string {
	if m == nil || m.Markdown == nil {
		return ""
	}
	return *m.Markdown
}

// GetText returns the Text field if it's non-nil, zero value otherwise.
func (m *Message) GetText() string {
	if m == nil || m.Text == nil {
		return ""
	}
	return *m.Text
}

// GetArtifactID returns the ArtifactID field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetArtifactID() string {
	if p == nil || p.ArtifactID == nil {
		return ""
	}
	return *p.ArtifactID
}

// GetCodeReviewID returns the CodeReviewID field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetCodeReviewID() int {
	if p == nil || p.CodeReviewID == nil {
		return 0
	}
	return *p.CodeReviewID
}

// GetCreatedBy returns the CreatedBy field.
func (p *PullRequestResource) GetCreatedBy() *AuthorRef {
	if p == nil {
		return nil
	}
	return p.CreatedBy
}

// GetCreationDate returns the CreationDate field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetCreationDate() time.Time {
	if p == nil || p.CreationDate == nil {
		return time.Time{}
	}
	return *p.CreationDate
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetIsDraft returns the IsDraft field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetIsDraft() bool {
	if p == nil || p.IsDraft == nil {
		return false
	}
	return *p.IsDraft
}

// GetLastMergeCommit returns the LastMergeCommit field.
func (p *PullRequestResource) GetLastMergeCommit() *MergeCommit {
	if p == nil {
		return nil
	}
	return p.LastMergeCommit
}

// GetLastMergeSourceCommit returns the LastMergeSourceCommit field.
func (p *PullRequestResource) GetLastMergeSourceCommit() *MergeCommit {
	if p == nil {
		return nil
	}
	return p.LastMergeSourceCommit
}

// GetLastMergeTargetCommit returns the LastMergeTargetCommit field.
func (p *PullRequestResource) GetLastMergeTargetCommit() *MergeCommit {
	if p == nil {
		return nil
	}
	return p.LastMergeTargetCommit
}

// GetLinks returns the Links field.
func (p *PullRequestResource) GetLinks() *Links {
	if p == nil {
		return nil
	}
	return p.Links
}

// GetMergeID returns the MergeID field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetMergeID() string {
	if p == nil || p.MergeID == nil {
		return ""
	}
	return *p.MergeID
}

// GetMergeStatus returns the MergeStatus field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetMergeStatus() string {
	if p == nil || p.MergeStatus == nil {
		return ""
	}
	return *p.MergeStatus
}

// GetPullRequestID returns the PullRequestID field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetPullRequestID() int {
	if p == nil || p.PullRequestID == nil {
		return 0
	}
	return *p.PullRequestID
}

// GetRepo returns the Repo field.
func (p *PullRequestResource) GetRepo() *Repo {
	if p == nil {
		return nil
	}
	return p.Repo
}

// GetSourceRefName returns the SourceRefName field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetSourceRefName() string {
	if p == nil || p.SourceRefName == nil {
		return ""
	}
	return *p.SourceRefName
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetStatus() string {
	if p == nil || p.Status == nil {
		return ""
	}
	return *p.Status
}

// GetSupportsIterations returns the SupportsIterations field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetSupportsIterations() bool {
	if p == nil || p.SupportsIterations == nil {
		return false
	}
	return *p.SupportsIterations
}

// GetTargetRefName returns the TargetRefName field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetTargetRefName() string {
	if p == nil || p.TargetRefName == nil {
		return ""
	}
	return *p.TargetRefName
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetTitle() string {
	if p == nil || p.Title == nil {
		return ""
	}
	return *p.Title
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (p *PullRequestResource) GetURL() string {
	if p == nil || p.URL == nil {
		return ""
	}
	return *p.URL
}

// GetAuthor returns the Author field.
func (p *PushResource) GetAuthor() *AuthorRef {
	if p == nil {
		return nil
	}
	return p.Author
}

// GetChangeSetID returns the ChangeSetID field if it's non-nil, zero value otherwise.
func (p *PushResource) GetChangeSetID() int {
	if p == nil || p.ChangeSetID == nil {
		return 0
	}
	return *p.ChangeSetID
}

// GetCheckedInBy returns the CheckedInBy field.
func (p *PushResource) GetCheckedInBy() *AuthorRef {
	if p == nil {
		return nil
	}
	return p.CheckedInBy
}

// GetComment returns the Comment field if it's non-nil, zero value otherwise.
func (p *PushResource) GetComment() string {
	if p == nil || p.Comment == nil {
		return ""
	}
	return *p.Comment
}

// GetCreatedDate returns the CreatedDate field if it's non-nil, zero value otherwise.
func (p *PushResource) GetCreatedDate() time.Time {
	if p == nil || p.CreatedDate == nil {
		return time.Time{}
	}
	return *p.CreatedDate
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (p *PushResource) GetURL() string {
	if p == nil || p.URL == nil {
		return ""
	}
	return *p.URL
}

// GetProject returns the Project field.
func (r *Repo) GetProject() *Project {
	if r == nil {
		return nil
	}
	return r.Project
}

// GetAccount returns the Account field.
func (r *ResourceContainers) GetAccount() *ResourceRef {
	if r == nil {
		return nil
	}
	return r.Account
}

// GetCollection returns the Collection field.
func (r *ResourceContainers) GetCollection() *ResourceRef {
	if r == nil {
		return nil
	}
	return r.Collection
}

// GetProject returns the Project field.
func (r *ResourceContainers) GetProject() *ResourceRef {
	if r == nil {
		return nil
	}
	return r.Project
}

// GetBaseURL returns the BaseURL field if it's non-nil, zero value otherwise.
func (r *ResourceRef) GetBaseURL() string {
	if r == nil || r.BaseURL == nil {
		return ""
	}
	return *r.BaseURL
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (r *ResourceRef) GetID() string {
	if r == nil || r.ID == nil {
		return ""
	}
	return *r.ID
}
